"""empty message

Revision ID: 00de89ead938
Revises: 5e3961f7e5ab
Create Date: 2021-09-01 15:29:02.552156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00de89ead938'
down_revision = '5e3961f7e5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('aircraft', sa.Column('tail_number', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft', 'tail_number')
    op.drop_column('aircraft', 'year')
    # ### end Alembic commands ###
