"""empty message

Revision ID: 5e3961f7e5ab
Revises: dcbbcfe94944
Create Date: 2021-08-26 07:30:37.456171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3961f7e5ab'
down_revision = 'dcbbcfe94944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('need_performance', sa.Boolean(), nullable=True))
    op.drop_column('aircraft', 'need_performace')
    op.add_column('users', sa.Column('is_performance', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_performace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_performace', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_performance')
    op.add_column('aircraft', sa.Column('need_performace', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('aircraft', 'need_performance')
    # ### end Alembic commands ###
