"""empty message

Revision ID: d922b34118fc
Revises: 
Create Date: 2021-08-26 07:11:56.292096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd922b34118fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_IR', sa.Boolean(), nullable=True),
    sa.Column('is_CSEL', sa.Boolean(), nullable=True),
    sa.Column('is_CMEL', sa.Boolean(), nullable=True),
    sa.Column('is_ATP', sa.Boolean(), nullable=True),
    sa.Column('is_CFI', sa.Boolean(), nullable=True),
    sa.Column('is_CFII', sa.Boolean(), nullable=True),
    sa.Column('is_MEI', sa.Boolean(), nullable=True),
    sa.Column('is_complex', sa.Boolean(), nullable=True),
    sa.Column('is_performace', sa.Boolean(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.Column('home_airport', sa.String(length=5), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('cover_img', sa.String(), nullable=False),
    sa.Column('avionics', sa.String(), nullable=False),
    sa.Column('ifr_cert', sa.Boolean(), nullable=True),
    sa.Column('need_IR', sa.Boolean(), nullable=True),
    sa.Column('need_CSEL', sa.Boolean(), nullable=True),
    sa.Column('need_CMEL', sa.Boolean(), nullable=True),
    sa.Column('need_ATP', sa.Boolean(), nullable=True),
    sa.Column('need_CFI', sa.Boolean(), nullable=True),
    sa.Column('need_CFII', sa.Boolean(), nullable=True),
    sa.Column('need_MEI', sa.Boolean(), nullable=True),
    sa.Column('need_complex', sa.Boolean(), nullable=True),
    sa.Column('need_performace', sa.Boolean(), nullable=True),
    sa.Column('airport', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('gph', sa.Integer(), nullable=True),
    sa.Column('fuel_capacity', sa.Integer(), nullable=True),
    sa.Column('cruise_speed', sa.Integer(), nullable=True),
    sa.Column('usable_load', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('poh', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aircraft')
    op.drop_table('users')
    # ### end Alembic commands ###
